// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

import * as RootRoute from '@/app/page.info';
import * as BlogDetailsRoute from '@/app/blog/[id]/page.info';
import * as BlogsRoute from '@/app/blogs/page.info';
import * as ProjectsRoute from '@/app/projects/page.info';
import * as SkillsRoute from '@/app/skills/page.info';

export const Root = makeRoute('/', {
  ...defaultInfo,
  ...RootRoute.Route,
});

export const BlogDetails = makeRoute('/blog/[id]', {
  ...defaultInfo,
  ...BlogDetailsRoute.Route,
});
export const Blogs = makeRoute('/blogs', {
  ...defaultInfo,
  ...BlogsRoute.Route,
});
export const Projects = makeRoute('/projects', {
  ...defaultInfo,
  ...ProjectsRoute.Route,
});
export const Skills = makeRoute('/skills', {
  ...defaultInfo,
  ...SkillsRoute.Route,
});
